//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPPlany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kierunek
    {
        public Kierunek()
        {
            this.Katedra = new HashSet<Katedra>();
        }
    
        public int id_kierunek { get; set; }
        public string nazwa { get; set; }
        public string wydział { get; set; }
    
        public virtual ICollection<Katedra> Katedra { get; set; }
    }
}
