//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPPlany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy
    {
        public int id_pracownik { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public Nullable<int> rok_urodzenia { get; set; }
        public Nullable<bool> obecnosc_dzieci { get; set; }
        public Nullable<int> ile_dzieci { get; set; }
        public string plec { get; set; }
        public Nullable<bool> czy_wykladowca { get; set; }
        public string kategoria { get; set; }
        public string stopien { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public int Katedra_id_katedra { get; set; }
        public int Przedmioty_id_przedmiot { get; set; }
    
        public virtual Katedra Katedra { get; set; }
        public virtual Przedmioty Przedmioty { get; set; }
    }
}
