<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PracownikMain.aspx.cs" Inherits="ASPPlany.PracownikMain" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Pracownik</title>
</head>
<body style="height: 671px; width: 2080px;">
    
    <form id="form1" runat="server">
        <asp:Panel ID="Panel1" runat="server" BackColor="#C66300" Height="50px">
            <asp:Button ID="btnHome" runat="server" Text="Strona Główna" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" Width="100px" OnClick="btnHome_Click" />
            &nbsp;<asp:Button ID="btnPrzedmioty" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnPrzedmioty_Click" Text="Przedmioty" Width="120px" />
            <asp:Button ID="btnStudenci" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnStudenci_Click" Text="Studenci" Width="120px" />
            <asp:Button ID="btnSpecjalnosci" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnSpecjalnosci_Click" Text="Specjalności" Width="120px" />
            <asp:Button ID="btnKierunki" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnKierunki_Click" Text="Kierunki" Width="100px" />
            &nbsp;<asp:Button ID="btnKatedry" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnKatedry_Click" Text="Katedry" Width="120px" />
            <asp:Button ID="btnStypendia" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnStypendia_Click" Text="Stypendia" Width="120px" />
            <asp:Button ID="btnPracownicy" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnPracownicy_Click" Text="Pracownicy" Width="120px" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnWyloguj" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnWyloguj_Click" Text="Wyloguj" Width="90px" />
        </asp:Panel>
        <asp:Panel ID="Panel2" runat="server" BackColor="#436280" Height="622px">
            <br />
            <br />
            <asp:Label ID="Label1" runat="server" Font-Bold="True" ForeColor="White" Text="Zalogowany jako : "></asp:Label>
            <br />
            <br />
            <br />
            <asp:MultiView ID="MultiView1" runat="server">
                <asp:View ID="Pracownicy" runat="server">
                    <asp:GridView ID="GridView7" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_pracownik" DataSourceID="PracownicySqlDataSource" Width="634px" AllowSorting="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black">
                        <Columns>
                            <asp:BoundField DataField="id_pracownik" HeaderText="id_pracownik" InsertVisible="False" ReadOnly="True" SortExpression="id_pracownik" />
                            <asp:BoundField DataField="imie" HeaderText="imie" SortExpression="imie" />
                            <asp:BoundField DataField="nazwisko" HeaderText="nazwisko" SortExpression="nazwisko" />
                            <asp:BoundField DataField="rok_urodzenia" HeaderText="rok_urodzenia" SortExpression="rok_urodzenia" />
                            <asp:CheckBoxField DataField="obecnosc_dzieci" HeaderText="obecnosc_dzieci" SortExpression="obecnosc_dzieci" />
                            <asp:BoundField DataField="ile_dzieci" HeaderText="ile_dzieci" SortExpression="ile_dzieci" />
                            <asp:BoundField DataField="plec" HeaderText="plec" SortExpression="plec" />
                            <asp:CheckBoxField DataField="czy_wykladowca" HeaderText="czy_wykladowca" SortExpression="czy_wykladowca" />
                            <asp:BoundField DataField="kategoria" HeaderText="kategoria" SortExpression="kategoria" />
                            <asp:BoundField DataField="stopien" HeaderText="stopien" SortExpression="stopien" />
                            <asp:BoundField DataField="login" HeaderText="login" SortExpression="login" />
                            <asp:BoundField DataField="haslo" HeaderText="haslo" SortExpression="haslo" />
                            <asp:TemplateField HeaderText="Katedra_id_katedra" SortExpression="Katedra_id_katedra">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="KatSqlDataSource1" DataTextField="nazwa" DataValueField="id_katedra" SelectedValue='<%# Bind("Katedra_id_katedra") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="KatSqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Katedra]"></asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("Katedra_id_katedra") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Przedmioty_id_przedmiot" SortExpression="Przedmioty_id_przedmiot">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSource1" DataTextField="nazwa" DataValueField="id_przedmiot" SelectedValue='<%# Bind("Przedmioty_id_przedmiot") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT [id_przedmiot], [nazwa] FROM [Przedmioty]"></asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("Przedmioty_id_przedmiot") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="Gray" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                    <br />
                    <asp:Panel ID="pDodajPracownik" runat="server" Height="472px" Visible="False" Width="529px">
                        <asp:Label ID="Label28" runat="server" Text="Imię : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbImiePracownik" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label29" runat="server" Text="Nazwisko : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbNazwiskoPracownik" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label30" runat="server" Text="Rok urodzenia : "></asp:Label>
                        &nbsp;&nbsp;
                        <asp:TextBox ID="tbRokUrodzeniaPracownik" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label31" runat="server" Text="Obecność dzieci : "></asp:Label>
                        <asp:CheckBox ID="chbObecnoscDzieciPracownik" runat="server" />
                        <br />
                        <asp:Label ID="Label32" runat="server" Text="Ile dzieci : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbIleDzieciPracownik" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label33" runat="server" Text="Płeć : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbPlecPracownik" runat="server"></asp:TextBox>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <br />
                        <asp:Label ID="Label35" runat="server" Text="Login : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbLoginPracownik" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label36" runat="server" Text="Hasło : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbHasloPracownik" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label40" runat="server" Text="Czy wykładowca : "></asp:Label>
                        <asp:CheckBox ID="chbCzyWykladowcaPracownik" runat="server" />
                        <br />
                        <asp:Label ID="Label38" runat="server" Text="Katedra : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:DropDownList ID="ddlKatedraPracownik" runat="server" DataSourceID="ddlKatedraPracownikSqlDataSource" DataTextField="nazwa" DataValueField="id_katedra">
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="ddlKatedraPracownikSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Katedra]"></asp:SqlDataSource>
                        <br />
                        <asp:Label ID="Label39" runat="server" Text="Przedmiot : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:DropDownList ID="ddlPrzedmiotPracownik" runat="server" DataSourceID="przedmiotPracownikSqlDataSource" DataTextField="nazwa" DataValueField="id_przedmiot">
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="przedmiotPracownikSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Przedmioty]"></asp:SqlDataSource>
                        <br />
                        <asp:Button ID="btnZapiszPracownik" runat="server" Height="50px" OnClick="btnZapiszPracownik_Click" Text="Zapisz" Width="120px" />
                    </asp:Panel>
                    <br />
                    <asp:Button ID="btnDodajPracownik" runat="server" Height="50px" OnClick="btnDodajPracownik_Click" Text="Dodaj" Width="120px" />
                    <asp:SqlDataSource ID="PracownicySqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" DeleteCommand="DELETE FROM [Pracownicy] WHERE [id_pracownik] = @id_pracownik" InsertCommand="INSERT INTO [Pracownicy] ([imie], [nazwisko], [rok_urodzenia], [obecnosc_dzieci], [ile_dzieci], [plec], [czy_wykladowca], [kategoria], [stopien], [login], [haslo], [Katedra_id_katedra], [Przedmioty_id_przedmiot]) VALUES (@imie, @nazwisko, @rok_urodzenia, @obecnosc_dzieci, @ile_dzieci, @plec, @czy_wykladowca, @kategoria, @stopien, @login, @haslo, @Katedra_id_katedra, @Przedmioty_id_przedmiot)" SelectCommand="SELECT * FROM [Pracownicy]" UpdateCommand="UPDATE [Pracownicy] SET [imie] = @imie, [nazwisko] = @nazwisko, [rok_urodzenia] = @rok_urodzenia, [obecnosc_dzieci] = @obecnosc_dzieci, [ile_dzieci] = @ile_dzieci, [plec] = @plec, [czy_wykladowca] = @czy_wykladowca, [kategoria] = @kategoria, [stopien] = @stopien, [login] = @login, [haslo] = @haslo, [Katedra_id_katedra] = @Katedra_id_katedra, [Przedmioty_id_przedmiot] = @Przedmioty_id_przedmiot WHERE [id_pracownik] = @id_pracownik">
                        <DeleteParameters>
                            <asp:Parameter Name="id_pracownik" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="imie" Type="String" />
                            <asp:Parameter Name="nazwisko" Type="String" />
                            <asp:Parameter Name="rok_urodzenia" Type="Int32" />
                            <asp:Parameter Name="obecnosc_dzieci" Type="Boolean" />
                            <asp:Parameter Name="ile_dzieci" Type="Int32" />
                            <asp:Parameter Name="plec" Type="String" />
                            <asp:Parameter Name="czy_wykladowca" Type="Boolean" />
                            <asp:Parameter Name="kategoria" Type="String" />
                            <asp:Parameter Name="stopien" Type="String" />
                            <asp:Parameter Name="login" Type="String" />
                            <asp:Parameter Name="haslo" Type="String" />
                            <asp:Parameter Name="Katedra_id_katedra" Type="Int32" />
                            <asp:Parameter Name="Przedmioty_id_przedmiot" Type="Int32" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="imie" Type="String" />
                            <asp:Parameter Name="nazwisko" Type="String" />
                            <asp:Parameter Name="rok_urodzenia" Type="Int32" />
                            <asp:Parameter Name="obecnosc_dzieci" Type="Boolean" />
                            <asp:Parameter Name="ile_dzieci" Type="Int32" />
                            <asp:Parameter Name="plec" Type="String" />
                            <asp:Parameter Name="czy_wykladowca" Type="Boolean" />
                            <asp:Parameter Name="kategoria" Type="String" />
                            <asp:Parameter Name="stopien" Type="String" />
                            <asp:Parameter Name="login" Type="String" />
                            <asp:Parameter Name="haslo" Type="String" />
                            <asp:Parameter Name="Katedra_id_katedra" Type="Int32" />
                            <asp:Parameter Name="Przedmioty_id_przedmiot" Type="Int32" />
                            <asp:Parameter Name="id_pracownik" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </asp:View>
                <asp:View ID="Stypendia" runat="server">
                    <asp:GridView ID="GridView6" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_stypendium" DataSourceID="StypendiaSqlDataSource" Width="322px" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black">
                        <Columns>
                            <asp:BoundField DataField="id_stypendium" HeaderText="id_stypendium" InsertVisible="False" ReadOnly="True" SortExpression="id_stypendium" Visible="False" />
                            <asp:BoundField DataField="rodziaj" HeaderText="rodziaj" SortExpression="rodziaj" />
                            <asp:BoundField DataField="kwota" HeaderText="kwota" SortExpression="kwota" />
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#808080" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                    <br />
                    <asp:Panel ID="pDodajStypendium" runat="server" Height="157px" Visible="False" Width="398px">
                        <asp:Label ID="Label26" runat="server" Text="Rodzaj : "></asp:Label>
                        &nbsp;
                        <asp:TextBox ID="tbRodzajStypendium" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label27" runat="server" Text="Kwota : "></asp:Label>
                        &nbsp;
                        <asp:TextBox ID="tbKwotaStypendium" runat="server"></asp:TextBox>
                        <br />
                        <br />
                        <asp:Button ID="btnZapiszStypendia" runat="server" Height="50px" OnClick="btnZapiszStypendia_Click" Text="Zapisz" Width="120px" />
                    </asp:Panel>
                    <asp:Button ID="btnDodajStypendia" runat="server" Height="50px" OnClick="btnDodajStypendia_Click" Text="Dodaj" Width="120px" />
                    <br />
                    <asp:SqlDataSource ID="StypendiaSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" DeleteCommand="DELETE FROM [Stypendium] WHERE [id_stypendium] = @id_stypendium" InsertCommand="INSERT INTO [Stypendium] ([rodziaj], [kwota]) VALUES (@rodziaj, @kwota)" SelectCommand="SELECT * FROM [Stypendium]" UpdateCommand="UPDATE [Stypendium] SET [rodziaj] = @rodziaj, [kwota] = @kwota WHERE [id_stypendium] = @id_stypendium">
                        <DeleteParameters>
                            <asp:Parameter Name="id_stypendium" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="rodziaj" Type="String" />
                            <asp:Parameter Name="kwota" Type="Decimal" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="rodziaj" Type="String" />
                            <asp:Parameter Name="kwota" Type="Decimal" />
                            <asp:Parameter Name="id_stypendium" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </asp:View>
                <asp:View ID="Katedry" runat="server">
                    <asp:GridView ID="GridView5" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_katedra" DataSourceID="KatedraSqlDataSource" Height="133px" OnSelectedIndexChanged="GridView5_SelectedIndexChanged" Width="527px" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black">
                        <Columns>
                            <asp:BoundField DataField="id_katedra" HeaderText="id_katedra" InsertVisible="False" ReadOnly="True" SortExpression="id_katedra" Visible="False" />
                            <asp:BoundField DataField="nazwa" HeaderText="nazwa" SortExpression="nazwa" />
                            <asp:TemplateField HeaderText="Kierunek_id_kierunek" SortExpression="Kierunek_id_kierunek">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList3" runat="server" DataSourceID="SqlDataSource1" DataTextField="nazwa" DataValueField="id_kierunek" SelectedValue='<%# Bind("Kierunek_id_kierunek") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT [id_kierunek], [nazwa] FROM [Kierunek]"></asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("Kierunek_id_kierunek") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#808080" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                    <asp:Panel ID="pDodajKatedre" runat="server" Height="206px" Visible="False" Width="515px">
                        <br />
                        <asp:Label ID="Label24" runat="server" Text="Nazwa : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbNazwaKatedra" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label25" runat="server" Text="Kierunek : "></asp:Label>
                        &nbsp;<asp:DropDownList ID="ddlKierunekKatedra" runat="server" DataSourceID="KatedraKierunekSqlDataSource" DataTextField="nazwa" DataValueField="id_kierunek">
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="KatedraKierunekSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Kierunek]"></asp:SqlDataSource>
                        <br />
                        <br />
                        <asp:Button ID="btnZapiszKatedre" runat="server" Height="50px" OnClick="btnZapiszKatedre_Click" Text="Zapisz" Width="120px" />
                    </asp:Panel>
                    <asp:Button ID="btnDodajKatedre" runat="server" Height="50px" OnClick="btnDodajKatedre_Click" Text="Dodaj" Width="120px" />
                    <br />
                    <asp:SqlDataSource ID="KatedraSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" DeleteCommand="DELETE FROM [Katedra] WHERE [id_katedra] = @id_katedra" InsertCommand="INSERT INTO [Katedra] ([nazwa], [Kierunek_id_kierunek]) VALUES (@nazwa, @Kierunek_id_kierunek)" SelectCommand="SELECT * FROM [Katedra]" UpdateCommand="UPDATE [Katedra] SET [nazwa] = @nazwa, [Kierunek_id_kierunek] = @Kierunek_id_kierunek WHERE [id_katedra] = @id_katedra">
                        <DeleteParameters>
                            <asp:Parameter Name="id_katedra" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="Kierunek_id_kierunek" Type="Int32" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="Kierunek_id_kierunek" Type="Int32" />
                            <asp:Parameter Name="id_katedra" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </asp:View>
                <asp:View ID="Kierunki" runat="server">
                    <asp:GridView ID="GridView4" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_kierunek" DataSourceID="kierunekSqlDataSource" Width="362px" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black">
                        <Columns>
                            <asp:BoundField DataField="id_kierunek" HeaderText="id_kierunek" InsertVisible="False" ReadOnly="True" SortExpression="id_kierunek" Visible="False" />
                            <asp:BoundField DataField="nazwa" HeaderText="nazwa" SortExpression="nazwa" />
                            <asp:BoundField DataField="wydział" HeaderText="wydział" SortExpression="wydział" />
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#808080" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                    <br />
                    <asp:Panel ID="pDodajKierunek" runat="server" Height="130px" Visible="False" Width="311px">
                        <asp:Label ID="Label22" runat="server" Text="Nazwa : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbNazwaKierunek" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label23" runat="server" Text="Wydział : "></asp:Label>
                        &nbsp;&nbsp;
                        <asp:TextBox ID="tbWydzialKierunek" runat="server"></asp:TextBox>
                        <br />
                        <br />
                        <asp:Button ID="btnZapiszKierunek" runat="server" Height="50px" OnClick="btnZapiszKierunek_Click" Text="Zapisz" Width="120px" />
                    </asp:Panel>
                    <asp:Button ID="btnDodajKierunek" runat="server" Height="50px" OnClick="btnDodajKierunek_Click" Text="Dodaj" Width="120px" />
                    <br />
                    <asp:SqlDataSource ID="kierunekSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" DeleteCommand="DELETE FROM [Kierunek] WHERE [id_kierunek] = @id_kierunek" InsertCommand="INSERT INTO [Kierunek] ([nazwa], [wydział]) VALUES (@nazwa, @wydział)" SelectCommand="SELECT * FROM [Kierunek]" UpdateCommand="UPDATE [Kierunek] SET [nazwa] = @nazwa, [wydział] = @wydział WHERE [id_kierunek] = @id_kierunek">
                        <DeleteParameters>
                            <asp:Parameter Name="id_kierunek" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="wydział" Type="String" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="wydział" Type="String" />
                            <asp:Parameter Name="id_kierunek" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </asp:View>
                <asp:View ID="Specjalnosci" runat="server">
                    <asp:GridView ID="GridView3" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_specjalnosc" DataSourceID="SqlDataSource7" Width="356px" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black">
                        <Columns>
                            <asp:BoundField DataField="id_specjalnosc" HeaderText="id_specjalnosc" InsertVisible="False" ReadOnly="True" SortExpression="id_specjalnosc" Visible="False" />
                            <asp:BoundField DataField="nazwa" HeaderText="nazwa" SortExpression="nazwa" />
                            <asp:BoundField DataField="stopien" HeaderText="stopien" SortExpression="stopien" />
                            <asp:TemplateField HeaderText="Katedra_id_katedra" SortExpression="Katedra_id_katedra">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList4" runat="server" DataSourceID="SqlDataSource1" DataTextField="nazwa" DataValueField="id_katedra" SelectedValue='<%# Bind("Katedra_id_katedra") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT [id_katedra], [nazwa] FROM [Katedra]"></asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("Katedra_id_katedra") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#808080" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                    <br />
                    <asp:Panel ID="pDodajSpecjalnosc" runat="server" Height="179px" Visible="False" Width="640px">
                        <asp:Label ID="Label19" runat="server" Text="Nazwa : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbNazwaSpecjalnosc" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label20" runat="server" Text="Stopień : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbStopienSpecjalnosc" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label21" runat="server" Text="Katedra : "></asp:Label>
                        &nbsp;&nbsp;
                        <asp:DropDownList ID="ddlKatedraSpecjalnosc" runat="server" DataSourceID="ddlSqlDataSourceKatedraInSpecjalnosc" DataTextField="nazwa" DataValueField="id_katedra">
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="ddlSqlDataSourceKatedraInSpecjalnosc" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Katedra]"></asp:SqlDataSource>
                        <asp:Button ID="btnZapiszSpecjalnosc" runat="server" Height="50px" OnClick="btnZapiszSpecjalnosc_Click" Text="Zapisz" Width="120px" />
                        <br />
                    </asp:Panel>
                    <asp:Button ID="btnDodajSpecjalnosc" runat="server" Height="50px" OnClick="btnDodajSpecjalnosc_Click" Text="Dodaj" Width="120px" />
                    <br />
                    <asp:SqlDataSource ID="SqlDataSource7" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" DeleteCommand="DELETE FROM [Specjalnosc] WHERE [id_specjalnosc] = @id_specjalnosc" InsertCommand="INSERT INTO [Specjalnosc] ([nazwa], [stopien], [Katedra_id_katedra]) VALUES (@nazwa, @stopien, @Katedra_id_katedra)" SelectCommand="SELECT * FROM [Specjalnosc]" UpdateCommand="UPDATE [Specjalnosc] SET [nazwa] = @nazwa, [stopien] = @stopien, [Katedra_id_katedra] = @Katedra_id_katedra WHERE [id_specjalnosc] = @id_specjalnosc">
                        <DeleteParameters>
                            <asp:Parameter Name="id_specjalnosc" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="stopien" Type="Int32" />
                            <asp:Parameter Name="Katedra_id_katedra" Type="Int32" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="stopien" Type="Int32" />
                            <asp:Parameter Name="Katedra_id_katedra" Type="Int32" />
                            <asp:Parameter Name="id_specjalnosc" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </asp:View>
                <asp:View ID="Studenci" runat="server">
                    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Studenci_ID" DataSourceID="SqlDataSource3" Width="885px" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black">
                        <Columns>
                            <asp:BoundField DataField="Studenci_ID" HeaderText="Studenci_ID" InsertVisible="False" ReadOnly="True" SortExpression="Studenci_ID" Visible="False" />
                            <asp:BoundField DataField="imie" HeaderText="imie" SortExpression="imie" />
                            <asp:BoundField DataField="nazwisko" HeaderText="nazwisko" SortExpression="nazwisko" />
                            <asp:BoundField DataField="rok_urodzenia" HeaderText="rok_urodzenia" SortExpression="rok_urodzenia" />
                            <asp:CheckBoxField DataField="obecnosc_dzieci" HeaderText="obecnosc_dzieci" SortExpression="obecnosc_dzieci" />
                            <asp:BoundField DataField="ile_dzieci" HeaderText="ile_dzieci" SortExpression="ile_dzieci" />
                            <asp:BoundField DataField="plec" HeaderText="plec" SortExpression="plec" />
                            <asp:BoundField DataField="grupa" HeaderText="grupa" SortExpression="grupa" />
                            <asp:BoundField DataField="haslo" HeaderText="haslo" SortExpression="haslo" />
                            <asp:BoundField DataField="login" HeaderText="login" SortExpression="login" />
                            <asp:TemplateField HeaderText="Specjalnosc_id_specjalnosc" SortExpression="Specjalnosc_id_specjalnosc">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList5" runat="server" DataSourceID="SpecjalnoscSqlDataSource" DataTextField="nazwa" DataValueField="id_specjalnosc" SelectedValue='<%# Bind("Specjalnosc_id_specjalnosc") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="SpecjalnoscSqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Specjalnosc]"></asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("Specjalnosc_id_specjalnosc") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Stypendium_id_stypendium" SortExpression="Stypendium_id_stypendium">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList6" runat="server" DataSourceID="StypendumSqlDataSource1" DataTextField="rodziaj" DataValueField="id_stypendium" SelectedValue='<%# Bind("Stypendium_id_stypendium") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="StypendumSqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Stypendium]"></asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("Stypendium_id_stypendium") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Katedra_id_katedra" SortExpression="Katedra_id_katedra">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList7" runat="server" DataSourceID="KatedraSqlDataSource1" DataTextField="nazwa" DataValueField="id_katedra" SelectedValue='<%# Bind("Katedra_id_katedra") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="KatedraSqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Katedra]"></asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("Katedra_id_katedra") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#808080" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                    <br />
                    <asp:Panel ID="pDodajStudenci" runat="server" Height="532px" Width="529px" Visible="False">
                        <asp:Label ID="Label7" runat="server" Text="Imię : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbImieStudenci" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label8" runat="server" Text="Nazwisko : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbNazwiskoStudenci" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label9" runat="server" Text="Rok urodzenia : "></asp:Label>
                        &nbsp;&nbsp;
                        <asp:TextBox ID="tbRokUrodzeniaStudenci" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label10" runat="server" Text="Obecność dzieci : "></asp:Label>
                        <asp:CheckBox ID="chbObecnoscDzieciStudenci" runat="server" />
                        <br />
                        <asp:Label ID="Label11" runat="server" Text="Ile dzieci : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbIleDzieciStudenci" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label12" runat="server" Text="Płeć : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbPlecStudenci" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label13" runat="server" Text="Grupa : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbGrupaStudenci" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label14" runat="server" Text="Login : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbLoginStudenci" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label15" runat="server" Text="Hasło : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbHasloStudenci" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label16" runat="server" Text="Specjalność : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:DropDownList ID="ddlSpecjalnoscStudenci" runat="server" DataSourceID="SqlDataSource4" DataTextField="nazwa" DataValueField="id_specjalnosc">
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Specjalnosc]"></asp:SqlDataSource>
                        <br />
                        <asp:Label ID="Label17" runat="server" Text="Katedra : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:DropDownList ID="ddlKatedraStudenci" runat="server" DataSourceID="SqlDataSource5" DataTextField="nazwa" DataValueField="id_katedra">
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="SqlDataSource5" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Katedra]"></asp:SqlDataSource>
                        <br />
                        <asp:Label ID="Label18" runat="server" Text="Stypendium : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:DropDownList ID="ddlStypendiumStudenci" runat="server" DataSourceID="SqlDataSource6" DataTextField="rodziaj" DataValueField="id_stypendium">
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="SqlDataSource6" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Stypendium]"></asp:SqlDataSource>
                        <br />
                        <asp:Button ID="btnZapiszStudenci" runat="server" Height="50px" OnClick="btnZapiszStudenci_Click" Text="Zapisz" Width="120px" />
                    </asp:Panel>
                    <asp:Button ID="btnDodajStudenci" runat="server" Height="50px" OnClick="btnDodajStudenci_Click" Text="Dodaj" Width="120px" />
                    <br />
                    <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" DeleteCommand="DELETE FROM [Studenci] WHERE [Studenci_ID] = @Studenci_ID" InsertCommand="INSERT INTO [Studenci] ([imie], [nazwisko], [rok_urodzenia], [obecnosc_dzieci], [ile_dzieci], [plec], [grupa], [haslo], [login], [Specjalnosc_id_specjalnosc], [Stypendium_id_stypendium], [Katedra_id_katedra]) VALUES (@imie, @nazwisko, @rok_urodzenia, @obecnosc_dzieci, @ile_dzieci, @plec, @grupa, @haslo, @login, @Specjalnosc_id_specjalnosc, @Stypendium_id_stypendium, @Katedra_id_katedra)" SelectCommand="SELECT * FROM [Studenci]" UpdateCommand="UPDATE [Studenci] SET [imie] = @imie, [nazwisko] = @nazwisko, [rok_urodzenia] = @rok_urodzenia, [obecnosc_dzieci] = @obecnosc_dzieci, [ile_dzieci] = @ile_dzieci, [plec] = @plec, [grupa] = @grupa, [haslo] = @haslo, [login] = @login, [Specjalnosc_id_specjalnosc] = @Specjalnosc_id_specjalnosc, [Stypendium_id_stypendium] = @Stypendium_id_stypendium, [Katedra_id_katedra] = @Katedra_id_katedra WHERE [Studenci_ID] = @Studenci_ID">
                        <DeleteParameters>
                            <asp:Parameter Name="Studenci_ID" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="imie" Type="String" />
                            <asp:Parameter Name="nazwisko" Type="String" />
                            <asp:Parameter Name="rok_urodzenia" Type="Int32" />
                            <asp:Parameter Name="obecnosc_dzieci" Type="Boolean" />
                            <asp:Parameter Name="ile_dzieci" Type="Int32" />
                            <asp:Parameter Name="plec" Type="String" />
                            <asp:Parameter Name="grupa" Type="String" />
                            <asp:Parameter Name="haslo" Type="String" />
                            <asp:Parameter Name="login" Type="String" />
                            <asp:Parameter Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                            <asp:Parameter Name="Stypendium_id_stypendium" Type="Int32" />
                            <asp:Parameter Name="Katedra_id_katedra" Type="Int32" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="imie" Type="String" />
                            <asp:Parameter Name="nazwisko" Type="String" />
                            <asp:Parameter Name="rok_urodzenia" Type="Int32" />
                            <asp:Parameter Name="obecnosc_dzieci" Type="Boolean" />
                            <asp:Parameter Name="ile_dzieci" Type="Int32" />
                            <asp:Parameter Name="plec" Type="String" />
                            <asp:Parameter Name="grupa" Type="String" />
                            <asp:Parameter Name="haslo" Type="String" />
                            <asp:Parameter Name="login" Type="String" />
                            <asp:Parameter Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                            <asp:Parameter Name="Stypendium_id_stypendium" Type="Int32" />
                            <asp:Parameter Name="Katedra_id_katedra" Type="Int32" />
                            <asp:Parameter Name="Studenci_ID" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </asp:View>
                <asp:View ID="Przedmioty" runat="server">
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_przedmiot" DataSourceID="SqlDataSource1" Width="542px" AllowSorting="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black">
                        <Columns>
                            <asp:BoundField DataField="id_przedmiot" HeaderText="id_przedmiot" InsertVisible="False" ReadOnly="True" SortExpression="id_przedmiot" />
                            <asp:BoundField DataField="nazwa" HeaderText="nazwa" SortExpression="nazwa" />
                            <asp:BoundField DataField="ile_godzin" HeaderText="ile_godzin" SortExpression="ile_godzin" />
                            <asp:BoundField DataField="typ_zajec" HeaderText="typ_zajec" SortExpression="typ_zajec" />
                            <asp:BoundField DataField="semestr" HeaderText="semestr" SortExpression="semestr" />
                            <asp:TemplateField HeaderText="Specjalnosc_id_specjalnosc" SortExpression="Specjalnosc_id_specjalnosc">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList8" runat="server" DataSourceID="SpecjalSqlDataSource1" DataTextField="nazwa" DataValueField="id_specjalnosc" SelectedValue='<%# Bind("Specjalnosc_id_specjalnosc") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="SpecjalSqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Specjalnosc]"></asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("Specjalnosc_id_specjalnosc") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="Gray" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" DeleteCommand="DELETE FROM [Przedmioty] WHERE [id_przedmiot] = @id_przedmiot" InsertCommand="INSERT INTO [Przedmioty] ([nazwa], [ile_godzin], [typ_zajec], [semestr], [Specjalnosc_id_specjalnosc]) VALUES (@nazwa, @ile_godzin, @typ_zajec, @semestr, @Specjalnosc_id_specjalnosc)" SelectCommand="SELECT * FROM [Przedmioty]" UpdateCommand="UPDATE [Przedmioty] SET [nazwa] = @nazwa, [ile_godzin] = @ile_godzin, [typ_zajec] = @typ_zajec, [semestr] = @semestr, [Specjalnosc_id_specjalnosc] = @Specjalnosc_id_specjalnosc WHERE [id_przedmiot] = @id_przedmiot">
                        <DeleteParameters>
                            <asp:Parameter Name="id_przedmiot" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="ile_godzin" Type="Int32" />
                            <asp:Parameter Name="typ_zajec" Type="String" />
                            <asp:Parameter Name="semestr" Type="Int32" />
                            <asp:Parameter Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                        </InsertParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="ile_godzin" Type="Int32" />
                            <asp:Parameter Name="typ_zajec" Type="String" />
                            <asp:Parameter Name="semestr" Type="Int32" />
                            <asp:Parameter Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                            <asp:Parameter Name="id_przedmiot" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                    <asp:Panel ID="pDodajPrzedmiot" runat="server" Height="224px" Visible="False" Width="499px">
                        <asp:Label ID="Label2" runat="server" Text="Nazwa : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbNazwaPrzedmiot" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label3" runat="server" Text="Ile godzin : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbIleGodzinPrzedmiot" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label4" runat="server" Text="Typ zajec : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbTypZajecPrzedmiot" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label5" runat="server" Text="Semestr : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbSemestrPrzedmiot" runat="server"></asp:TextBox>
                        <br />
                        <asp:Label ID="Label6" runat="server" Text="Specjalnosc : "></asp:Label>
                        <asp:DropDownList ID="ddlPrzedmiotSpecjalizacja" runat="server" DataSourceID="SqlDataSource2" DataTextField="nazwa" DataValueField="id_specjalnosc">
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Specjalnosc]"></asp:SqlDataSource>
                        <asp:Button ID="btnZapiszPrzedmiot" runat="server" Height="50px" OnClick="btnZapiszPrzedmiot_Click" Text="Zapisz" Width="120px" />
                        <br />
                    </asp:Panel>
                    <br />
                    <asp:Button ID="btnDodajPrzedmiot" runat="server" Height="50px" OnClick="btnDodajPrzedmiot_Click" Text="Dodaj" Width="120px" />
                    <br />
                </asp:View>
            </asp:MultiView>
        </asp:Panel>
    </form>
    
    </body>
</html>