<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WykladowcaMain.aspx.cs" Inherits="ASPPlany.WykladowcaMain" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Wykładowca</title>
</head>
<body style="height: 671px">
    
    <form id="form1" runat="server">
        <asp:Panel ID="Panel1" runat="server" BackColor="#C66300" Height="50px">
            <asp:Button ID="btnHome" runat="server" Text="Strona Główna" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" Width="120px" OnClick="btnHome_Click" />
            <asp:Button ID="btnPrzedmioty" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnPrzedmioty_Click" Text="Przedmioty" Width="120px" />
            <asp:Button ID="btnStudenci" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnStudenci_Click" Text="Studenci" Width="120px" />
            <asp:Button ID="btnSpecjalnosci" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnSpecjalnosci_Click" Text="Specjalności" Width="120px" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnWyloguj" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnWyloguj_Click" Text="Wyloguj" Width="90px" />
        </asp:Panel>
        <asp:Panel ID="Panel2" runat="server" BackColor="#436280" Height="622px">
            <br />
            <asp:Label ID="Label1" runat="server" Font-Bold="True" ForeColor="White" Text="Zalogowany jako : "></asp:Label>
            <br />
            <br />
            <asp:MultiView ID="MultiView1" runat="server">
                <asp:View ID="View3" runat="server">
                    <asp:GridView ID="GridView3" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="id_przedmiot" DataSourceID="SqlDataSource3" ForeColor="Black" OnSelectedIndexChanged="GridView3_SelectedIndexChanged" Width="439px" OnSelectedIndexChanging="GridView3_SelectedIndexChanging" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2">
                        <Columns>
                            <asp:CommandField ShowSelectButton="True" ShowEditButton="True" />
                            <asp:TemplateField HeaderText="id_przedmiot" InsertVisible="False" SortExpression="id_przedmiot" Visible="False">
                                <EditItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Eval("id_przedmiot") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("id_przedmiot") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="nazwa" SortExpression="nazwa">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("nazwa") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label2" runat="server" Text='<%# Bind("nazwa") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="ile_godzin" SortExpression="ile_godzin">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("ile_godzin") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label3" runat="server" Text='<%# Bind("ile_godzin") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="typ_zajec" SortExpression="typ_zajec">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("typ_zajec") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label4" runat="server" Text='<%# Bind("typ_zajec") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="semestr" SortExpression="semestr">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("semestr") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label5" runat="server" Text='<%# Bind("semestr") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Specjalnosc_id_specjalnosc" SortExpression="Specjalnosc_id_specjalnosc">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSource1" DataTextField="nazwa" DataValueField="id_specjalnosc" SelectedValue='<%# Bind("Specjalnosc_id_specjalnosc") %>'>
                                    </asp:DropDownList>
                                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT [id_specjalnosc], [nazwa] FROM [Specjalnosc]"></asp:SqlDataSource>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label7" runat="server" Text='<%# Eval("Specjalnosc_id_specjalnosc") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#808080" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                    <asp:Button ID="Button1" runat="server" Text="Szukaj" />
                    <br />
                    <asp:Panel ID="Panel3" runat="server" Height="326px" Visible="False" Width="1253px">
                        <asp:Label ID="Label2" runat="server" Text="Nazwa : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbNazwa" runat="server"></asp:TextBox>
                        <br />
                        <br />
                        <asp:Label ID="Label3" runat="server" Text="Ile godzin : "></asp:Label>
                        <asp:TextBox ID="tbIleGodzin" runat="server" OnTextChanged="TextBox2_TextChanged"></asp:TextBox>
                        <br />
                        <br />
                        <asp:Label ID="Label5" runat="server" Text="Typ zajec : "></asp:Label>
                        <asp:TextBox ID="tbTypZajec" runat="server"></asp:TextBox>
                        <br />
                        <br />
                        <asp:Label ID="Label4" runat="server" Text="Semestr : "></asp:Label>
                        &nbsp;
                        <asp:TextBox ID="tbSemestr" runat="server"></asp:TextBox>
                        <br />
                        <br />
                        <asp:Label ID="Label6" runat="server" Text="Specjalnosc : "></asp:Label>
                        <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource4" DataTextField="nazwa" DataValueField="id_specjalnosc">
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT [id_specjalnosc], [nazwa], [stopien], [Katedra_id_katedra] FROM [Specjalnosc]"></asp:SqlDataSource>
                        <br />
                        <br />
                        <asp:Button ID="btnZapisz" runat="server" Height="50px" OnClick="btnZapisz_Click" Text="Zapisz" Width="120px" />
                    </asp:Panel>
                    <asp:Button ID="btnDodaj" runat="server" Height="50px" OnClick="btnDodaj_Click" Text="Dodaj" Width="120px" />
                    <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Przedmioty] WHERE (([Specjalnosc_id_specjalnosc] = @Specjalnosc_id_specjalnosc) AND ([nazwa] = @nazwa))" DeleteCommand="DELETE FROM [Przedmioty] WHERE [id_przedmiot] = @id_przedmiot" InsertCommand="INSERT INTO [Przedmioty] ([nazwa], [ile_godzin], [typ_zajec], [semestr], [Specjalnosc_id_specjalnosc]) VALUES (@nazwa, @ile_godzin, @typ_zajec, @semestr, @Specjalnosc_id_specjalnosc)" UpdateCommand="UPDATE [Przedmioty] SET [nazwa] = @nazwa, [ile_godzin] = @ile_godzin, [typ_zajec] = @typ_zajec, [semestr] = @semestr, [Specjalnosc_id_specjalnosc] = @Specjalnosc_id_specjalnosc WHERE [id_przedmiot] = @id_przedmiot">
                        <DeleteParameters>
                            <asp:Parameter Name="id_przedmiot" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="ile_godzin" Type="Int32" />
                            <asp:Parameter Name="typ_zajec" Type="String" />
                            <asp:Parameter Name="semestr" Type="Int32" />
                            <asp:Parameter Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                        </InsertParameters>
                        <SelectParameters>
                            <asp:Parameter DefaultValue="1" Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                            <asp:ControlParameter ControlID="TextBox1" DefaultValue="Bazy Danych" Name="nazwa" PropertyName="Text" Type="String" />
                        </SelectParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="ile_godzin" Type="Int32" />
                            <asp:Parameter Name="typ_zajec" Type="String" />
                            <asp:Parameter Name="semestr" Type="Int32" />
                            <asp:Parameter Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                            <asp:Parameter Name="id_przedmiot" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </asp:View>
                <asp:View ID="View2" runat="server">
                    &nbsp;&nbsp;
                    <asp:Label ID="Label14" runat="server" Text="Grupa :"></asp:Label>
                    <br />
                    <asp:TextBox ID="TextBox5" runat="server"></asp:TextBox>
                    <asp:Button ID="Button2" runat="server" Text="Szukaj" />
                    &nbsp;
                    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" DataKeyNames="Studenci_ID" DataSourceID="SqlDataSource2" ForeColor="Black" Width="1096px">
                        <Columns>
                            <asp:BoundField DataField="Studenci_ID" HeaderText="Studenci_ID" InsertVisible="False" ReadOnly="True" SortExpression="Studenci_ID" Visible="False" />
                            <asp:BoundField DataField="imie" HeaderText="imie" SortExpression="imie" />
                            <asp:BoundField DataField="nazwisko" HeaderText="nazwisko" SortExpression="nazwisko" />
                            <asp:BoundField DataField="rok_urodzenia" HeaderText="rok_urodzenia" SortExpression="rok_urodzenia" />
                            <asp:CheckBoxField DataField="obecnosc_dzieci" HeaderText="obecnosc_dzieci" SortExpression="obecnosc_dzieci" />
                            <asp:BoundField DataField="ile_dzieci" HeaderText="ile_dzieci" SortExpression="ile_dzieci" />
                            <asp:BoundField DataField="plec" HeaderText="plec" SortExpression="plec" />
                            <asp:BoundField DataField="grupa" HeaderText="grupa" SortExpression="grupa" />
                            <asp:BoundField DataField="haslo" HeaderText="haslo" SortExpression="haslo" Visible="False" />
                            <asp:BoundField DataField="login" HeaderText="login" SortExpression="login" Visible="False" />
                            <asp:BoundField DataField="Specjalnosc_id_specjalnosc" HeaderText="Specjalnosc_id_specjalnosc" SortExpression="Specjalnosc_id_specjalnosc" Visible="False" />
                            <asp:BoundField DataField="Stypendium_id_stypendium" HeaderText="Stypendium_id_stypendium" SortExpression="Stypendium_id_stypendium" Visible="False" />
                            <asp:BoundField DataField="Katedra_id_katedra" HeaderText="Katedra_id_katedra" SortExpression="Katedra_id_katedra" Visible="False" />
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="Gray" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                    <br />
                    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Studenci] WHERE ([grupa] = @grupa)">
                        <SelectParameters>
                            <asp:ControlParameter ControlID="TextBox5" DefaultValue="Programowanie1" Name="grupa" PropertyName="Text" Type="String" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                </asp:View>
                <asp:View ID="View1" runat="server">
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="id_specjalnosc" DataSourceID="SqlDataSource1" ForeColor="Black" Width="432px" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2">
                        <Columns>
                            <asp:BoundField DataField="nazwa" HeaderText="nazwa" SortExpression="nazwa" />
                            <asp:BoundField DataField="stopien" HeaderText="stopien" SortExpression="stopien" />
                            <asp:BoundField DataField="id_specjalnosc" HeaderText="id_specjalnosc" InsertVisible="False" ReadOnly="True" SortExpression="id_specjalnosc" Visible="False" />
                            <asp:BoundField DataField="Katedra_id_katedra" HeaderText="Katedra_id_katedra" SortExpression="Katedra_id_katedra" Visible="False" />
                        </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                        <RowStyle BackColor="White" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#808080" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT [nazwa], [stopien], [id_specjalnosc], [Katedra_id_katedra] FROM [Specjalnosc] WHERE ([nazwa] = @nazwa)">
                        <SelectParameters>
                            <asp:Parameter DefaultValue="Programowanie Komputerów" Name="nazwa" Type="String" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                </asp:View>
            </asp:MultiView>
        </asp:Panel>
    </form>
    
    </body>
</html>