//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPPlany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Katedra
    {
        public Katedra()
        {
            this.Pracownicy = new HashSet<Pracownicy>();
            this.Specjalnosc = new HashSet<Specjalnosc>();
            this.Studenci = new HashSet<Studenci>();
        }
    
        public int id_katedra { get; set; }
        public string nazwa { get; set; }
        public int Kierunek_id_kierunek { get; set; }
    
        public virtual Kierunek Kierunek { get; set; }
        public virtual ICollection<Pracownicy> Pracownicy { get; set; }
        public virtual ICollection<Specjalnosc> Specjalnosc { get; set; }
        public virtual ICollection<Studenci> Studenci { get; set; }
    }
}
