//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPPlany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanyKsztalceniaEntities : DbContext
    {
        public PlanyKsztalceniaEntities()
            : base("name=PlanyKsztalceniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Katedra> Katedra { get; set; }
        public DbSet<Kierunek> Kierunek { get; set; }
        public DbSet<Pracownicy> Pracownicy { get; set; }
        public DbSet<Przedmioty> Przedmioty { get; set; }
        public DbSet<Specjalnosc> Specjalnosc { get; set; }
        public DbSet<Studenci> Studenci { get; set; }
        public DbSet<Stypendium> Stypendium { get; set; }
    }
}
