//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPPlany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Przedmioty
    {
        public Przedmioty()
        {
            this.Pracownicy = new HashSet<Pracownicy>();
        }
    
        public int id_przedmiot { get; set; }
        public string nazwa { get; set; }
        public Nullable<int> ile_godzin { get; set; }
        public string typ_zajec { get; set; }
        public Nullable<int> semestr { get; set; }
        public int Specjalnosc_id_specjalnosc { get; set; }
    
        public virtual ICollection<Pracownicy> Pracownicy { get; set; }
        public virtual Specjalnosc Specjalnosc { get; set; }
    }
}
