<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WykladowcaMain.aspx.cs" Inherits="ASPPlany.WykladowcaMain" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Wykładowca</title>
</head>
<body style="height: 671px">
    
    <form id="form1" runat="server">
        <asp:Panel ID="Panel1" runat="server" BackColor="#C66300" Height="50px">
            <asp:Button ID="btnHome" runat="server" Text="Strona Główna" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" Width="120px" OnClick="btnHome_Click" />
            <asp:Button ID="btnPrzedmioty" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnPrzedmioty_Click" Text="Przedmioty" Width="120px" />
            <asp:Button ID="btnStudenci" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnStudenci_Click" Text="Studenci" Width="120px" />
            <asp:Button ID="btnSpecjalnosci" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnSpecjalnosci_Click" Text="Specjalności" Width="120px" />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btnWyloguj" runat="server" BackColor="#C66300" BorderStyle="None" ForeColor="White" Height="50px" OnClick="btnWyloguj_Click" Text="Wyloguj" Width="90px" />
        </asp:Panel>
        <asp:Panel ID="Panel2" runat="server" BackColor="#436280" Height="622px">
            <br />
            <asp:Label ID="Label1" runat="server" Font-Bold="True" ForeColor="White" Text="Zalogowany jako : "></asp:Label>
            <br />
            <br />
            <asp:MultiView ID="MultiView1" runat="server">
                <asp:View ID="View3" runat="server">
                    <asp:GridView ID="GridView3" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="id_przedmiot" DataSourceID="SqlDataSource3" ForeColor="White" OnSelectedIndexChanged="GridView3_SelectedIndexChanged" Width="439px">
                        <Columns>
                            <asp:BoundField DataField="id_przedmiot" HeaderText="id_przedmiot" InsertVisible="False" ReadOnly="True" SortExpression="id_przedmiot" Visible="False" />
                            <asp:BoundField DataField="nazwa" HeaderText="nazwa" SortExpression="nazwa" />
                            <asp:BoundField DataField="ile_godzin" HeaderText="ile_godzin" SortExpression="ile_godzin" />
                            <asp:BoundField DataField="typ_zajec" HeaderText="typ_zajec" SortExpression="typ_zajec" />
                            <asp:BoundField DataField="semestr" HeaderText="semestr" SortExpression="semestr" />
                            <asp:BoundField DataField="Specjalnosc_id_specjalnosc" HeaderText="Specjalnosc_id_specjalnosc" SortExpression="Specjalnosc_id_specjalnosc" Visible="False" />
                        </Columns>
                    </asp:GridView>
                    <br />
                    <asp:Panel ID="Panel3" runat="server" Height="326px" Visible="False" Width="1253px">
                        <asp:Label ID="Label2" runat="server" Text="Nazwa : "></asp:Label>
                        &nbsp;&nbsp;&nbsp;
                        <asp:TextBox ID="tbNazwa" runat="server"></asp:TextBox>
                        <br />
                        <br />
                        <asp:Label ID="Label3" runat="server" Text="Ile godzin : "></asp:Label>
                        <asp:TextBox ID="tbIleGodzin" runat="server" OnTextChanged="TextBox2_TextChanged"></asp:TextBox>
                        <br />
                        <br />
                        <asp:Label ID="Label5" runat="server" Text="Typ zajec : "></asp:Label>
                        <asp:TextBox ID="tbTypZajec" runat="server"></asp:TextBox>
                        <br />
                        <br />
                        <asp:Label ID="Label4" runat="server" Text="Semestr : "></asp:Label>
                        &nbsp;
                        <asp:TextBox ID="tbSemestr" runat="server"></asp:TextBox>
                        <br />
                        <br />
                        <asp:Label ID="Label6" runat="server" Text="Specjalnosc : "></asp:Label>
                        <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource4" DataTextField="nazwa" DataValueField="id_specjalnosc">
                        </asp:DropDownList>
                        <asp:SqlDataSource ID="SqlDataSource4" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT [id_specjalnosc], [nazwa], [stopien], [Katedra_id_katedra] FROM [Specjalnosc]"></asp:SqlDataSource>
                        <br />
                        <br />
                        <asp:Button ID="btnZapisz" runat="server" Height="50px" OnClick="btnZapisz_Click" Text="Zapisz" Width="120px" />
                    </asp:Panel>
                    <asp:Button ID="btnDodaj" runat="server" Height="50px" OnClick="btnDodaj_Click" Text="Dodaj" Width="120px" />
                    <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT * FROM [Przedmioty] WHERE ([Specjalnosc_id_specjalnosc] = @Specjalnosc_id_specjalnosc)" DeleteCommand="DELETE FROM [Przedmioty] WHERE [id_przedmiot] = @id_przedmiot" InsertCommand="INSERT INTO [Przedmioty] ([nazwa], [ile_godzin], [typ_zajec], [semestr], [Specjalnosc_id_specjalnosc]) VALUES (@nazwa, @ile_godzin, @typ_zajec, @semestr, @Specjalnosc_id_specjalnosc)" UpdateCommand="UPDATE [Przedmioty] SET [nazwa] = @nazwa, [ile_godzin] = @ile_godzin, [typ_zajec] = @typ_zajec, [semestr] = @semestr, [Specjalnosc_id_specjalnosc] = @Specjalnosc_id_specjalnosc WHERE [id_przedmiot] = @id_przedmiot">
                        <DeleteParameters>
                            <asp:Parameter Name="id_przedmiot" Type="Int32" />
                        </DeleteParameters>
                        <InsertParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="ile_godzin" Type="Int32" />
                            <asp:Parameter Name="typ_zajec" Type="String" />
                            <asp:Parameter Name="semestr" Type="Int32" />
                            <asp:Parameter Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                        </InsertParameters>
                        <SelectParameters>
                            <asp:Parameter DefaultValue="1" Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                        </SelectParameters>
                        <UpdateParameters>
                            <asp:Parameter Name="nazwa" Type="String" />
                            <asp:Parameter Name="ile_godzin" Type="Int32" />
                            <asp:Parameter Name="typ_zajec" Type="String" />
                            <asp:Parameter Name="semestr" Type="Int32" />
                            <asp:Parameter Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                            <asp:Parameter Name="id_przedmiot" Type="Int32" />
                        </UpdateParameters>
                    </asp:SqlDataSource>
                </asp:View>
                <asp:View ID="View2" runat="server">
                    <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataSourceID="SqlDataSource2" ForeColor="White" Width="427px">
                        <Columns>
                            <asp:BoundField DataField="imie" HeaderText="imie" SortExpression="imie" />
                            <asp:BoundField DataField="nazwisko" HeaderText="nazwisko" SortExpression="nazwisko" />
                            <asp:BoundField DataField="rok_urodzenia" HeaderText="rok_urodzenia" SortExpression="rok_urodzenia" />
                            <asp:BoundField DataField="plec" HeaderText="plec" SortExpression="plec" />
                            <asp:BoundField DataField="grupa" HeaderText="grupa" SortExpression="grupa" />
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT [imie], [nazwisko], [rok_urodzenia], [plec], [grupa] FROM [Studenci] WHERE ([Specjalnosc_id_specjalnosc] = @Specjalnosc_id_specjalnosc)">
                        <SelectParameters>
                            <asp:Parameter DefaultValue="1" Name="Specjalnosc_id_specjalnosc" Type="Int32" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                </asp:View>
                <asp:View ID="View1" runat="server">
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="id_specjalnosc" DataSourceID="SqlDataSource1" ForeColor="White" Width="432px">
                        <Columns>
                            <asp:BoundField DataField="nazwa" HeaderText="nazwa" SortExpression="nazwa" />
                            <asp:BoundField DataField="stopien" HeaderText="stopien" SortExpression="stopien" />
                            <asp:BoundField DataField="id_specjalnosc" HeaderText="id_specjalnosc" InsertVisible="False" ReadOnly="True" SortExpression="id_specjalnosc" Visible="False" />
                            <asp:BoundField DataField="Katedra_id_katedra" HeaderText="Katedra_id_katedra" SortExpression="Katedra_id_katedra" Visible="False" />
                        </Columns>
                    </asp:GridView>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PlanyKsztalceniaConnectionString %>" SelectCommand="SELECT [nazwa], [stopien], [id_specjalnosc], [Katedra_id_katedra] FROM [Specjalnosc] WHERE ([nazwa] = @nazwa)">
                        <SelectParameters>
                            <asp:Parameter DefaultValue="Programowanie Komputerów" Name="nazwa" Type="String" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                </asp:View>
            </asp:MultiView>
        </asp:Panel>
    </form>
    
    </body>
</html>